name: firstOne

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v5.0.0

      - name: Set up go
        uses: actions/setup-go@v6.0.0

      - name: Run tests
        run: go test ./...
