name : firstOne

on:
  push:
    branches:
      -main 
  pull_request:
    branches:
      -main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -name: check
      uses: actions/checkout@v5.0.0
      run: npm test
