name : try
on : 
  push:
    branch:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name : check
      uses: actions/checkout@v5.0.0

    - name : "rntests"
      run : npm test

    - name : prinnnnnnnnnt
      run : echo "welcome and helloz"
